; PlatformIO Project Configuration File for RS485 Master-Slave Communication
;
; Target: ESP32 Dev Module (x2)
; Module: XY-017 RS485 to TTL (x2)
; Test Objective: Validate point-to-point communication between two ESP32 nodes

[env:rs485_master]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 

[env:rs485_slave]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
